# rustflags = [
#   "-C", "link-arg=-Tlink.x",
#   "-C", "link-arg=-Tdefmt.x",
# ]

# [build]
# target = "thumbv7em-none-eabihf"

# [env]
# DEFMT_LOG = "debug"

[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
rustflags = ["-C", "link-arg=-Tlink.x"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = [
  "probe-rs",
  "run",
  "--chip",
  "nRF52840_xxAA",
  "--log-format",
  "{L} {s}",
]